name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  full-pipeline:
    runs-on: 'ubuntu-18.04'
    steps:
      - uses: 'actions/checkout@v2'
        with:
          fetch-depth: '0'
      - uses: 'actions/setup-node@v1'
        with:
          node-version: '12.x'
      - name: npm install
        run: npm install
      - name: build
        run: npm run build
      - name: lint
        run: npm run lint
      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.11.10
        with:
          # This will be used for authentication. You can find it in your heroku homepage account settings
          heroku_api_key:
            # Email that you use with heroku
            ${{secrets.HEROKU_API_KEY}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          heroku_app_name: richen-phonebook
          healthcheck: 'https://richen-phonebook.herokuapp.com/health'
          checkstring: 'ok'
          delay: 10
          rollbackonhealthcheckfailed: true
        if: ( github.event_name == 'push' ) && success()
      - uses: 'actions/checkout@v2'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.34.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          INITIAL_VERSION: 1.0.0
          WITH_V: true
        if: (github.event_name == 'push') && !contains(github.event.head_commit.message, '#skip') && success()
